### ISSUE TITLE
ImportError: No module named dns_resolver

### ISSUE THREAD

**Issue by Lockzi** [runfalk/certbot-loopia#2]
Hej igen,

unfortunately I am getting this error.

Complete output:

```
An unexpected error occurred:
ImportError: No module named dns_resolver
Please see the logfile '/tmp/tmphBMytf' for more details.
```

/tmp/tmphBMytf
```
2017-06-05 19:27:46,859:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.14.2', 'console_scripts', 'certbot')()
  File "build/bdist.linux-armv7l/egg/certbot/main.py", line 722, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "build/bdist.linux-armv7l/egg/certbot/plugins/disco.py", line 193, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "build/bdist.linux-armv7l/egg/certbot/plugins/disco.py", line 40, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/home/openhabian/certbot-loopia/certbot_loopia.py", line 7, in <module>
    from acme.dns_resolver import DNS_AVAILABLE
ImportError: No module named dns_resolver
```

Any ideas? I see that your initial commits did not have this line #7 and instead relied on your loopialib.

**Comment by runfalk** [comment]
The `dns_resolver` has nothing to do with `loopialib`. It seems like `certbot` no longer provides that particular module. It was removed in late January (https://github.com/certbot/certbot/commit/be5bcfe463d9649c350181fe1a84e9d513db1ff3). Though my commit is barely a month old I wrote the code in December last year.

The workaround for now is to install an older certbot version, `acme==0.9.3` is known to work. If I understand the change history anything `<0.11` should work. I don't use the module myself because the method is so unreliable, so I don't know when I will get around to fix it.

**Comment by Lockzi** [comment]
Hej igen Runfalk,

Sorry to hear that the method is so unreliable that you're not using it anymore.

```
$pip list
acme (0.9.3)
asn1crypto (0.22.0)
bzr-etckeeper (0.0.0)
certbot (0.10.2)
certbot-loopia (0.1.0, /home/openhabian/certbot-loopia)
certifi (2017.4.17)
cffi (1.10.0)
chardet (3.0.3)
colorama (0.3.2)
ConfigArgParse (0.12.0)
configobj (5.0.6)
cryptography (1.9)
dnspython (1.12.0)
enum34 (1.1.6)
funcsigs (1.0.2)
future (0.16.0)
html5lib (0.999)
idna (2.5)
ipaddress (1.0.18)
loopialib (0.1.0)
mock (2.0.0)
ndg-httpsclient (0.3.2)
parsedatetime (2.4)
pbr (3.0.1)
pip (9.0.1)
pyasn1 (0.1.7)
pycparser (2.17)
pycrypto (2.6.1)
pyOpenSSL (0.14)
pyRFC3339 (1.0)
python-apt (0.9.3.12)
pytz (2017.2)
requests (2.17.3)
RPi.GPIO (0.6.3)
setuptools (5.5.1)
six (1.9.0)
tzupdate (1.2.0)
urllib3 (1.21.1)
wheel (0.24.0)
zope.component (4.3.0)
zope.event (4.2.0)
zope.interface (4.4.1)
```


So I am running acme=0.9.3 and certbot 0.10.2 with certbot-loopia from this repo.

Yet I now get the following error: 

```
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 7, in <module>
    from certbot.main import main
  File "/usr/local/lib/python2.7/dist-packages/certbot/main.py", line 11, in <module>
    import zope.component
ImportError: No module named component
```

Am I missing something?

**Comment by runfalk** [comment]
Something tells me that's without the virtualenv active. `zope.component` does contain `component`. That works in my environment. I don't have a working virtualenv to find out which package version that work.

```
(certbot-loopia:2.7)ante@Balthazar:~/dev/certbot-loopia (master)$ pip freeze|grep zope
zope.component==4.3.0
zope.event==4.2.0
zope.interface==4.4.0
(certbot-loopia:2.7) ~/dev/certbot-loopia (master)$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Python shell history and tab completion are enabled.
>>> import zope.component
>>> # No error
```

**Comment by runfalk** [comment]
Ok, so I've actually been in touch with Loopia and have some news about their guarantees. Firstly they cache things for 15 minutes, so you have to wait that. But then you also have to wait for the TTL of your domain apparently, which seems to default to 1 hour. I do however think 15 minutes will be enough for Let's Encrypt.

Once I get some more time I'll look into making a working version again.

**Comment by runfalk** [comment]
I've updated the plugin to work with the latest Certbot version. Let me know if it works for you. See the README for instructions on how to use it.

**Comment by asakth22** [comment]
Hi,

When I try to renew a domain I get this error,

Fault: <Fault 201: 'Method signature error: method getZoneRecords has no matching signature for the argument list: [string array string string]'>
An unexpected error occurred:
Fault: <Fault 201: 'Method signature error: method addZoneRecord has no matching signature for the argument list: [string array string string struct]'>

And this is the command I run,
#certbot certonly --authenticator certbot-loopia:auth --certbot-loopia:auth-credentials credentials.ini --server https://acme-v02.api.letsencrypt.org/directory -d example.com -d *.example.com

I use these versions,
certbot (0.37.2)
certbot-loopia (0.2.0)

What could be the reason ?

Br,
Anand

**Comment by runfalk** [comment]
Looks like it's treating your password as an array. Are you sure the ini is defined correctly?

**Comment by asakth22** [comment]
Actually I created another API user in loopia and then it worked. But the
plugin did not remove old 'TXT' records, I had to manually remove them. And
why is the 'TTL' set to 30. Even I was not able to change the value
manually.
