### ISSUE TITLE
Automatic wild-card domain renewal

### ISSUE THREAD

**Issue by tb-lund** [runfalk/certbot-loopia#7]
Hi Runfalk,

Thank you for great work with the loopia authenticator. I'm using it for wild-card domains and it is working very well for manual renewal. However, I'm having significant issues getting it working for automatic renewal of wild-card domains. 

The manual renewal works well using the following command:

`certbot certonly --authenticator certbot-loopia:auth --preferred-challenges=dns-01 --email email@gmail.com --certbot-loopia:auth-credentials /etc/letsencrypt/credentials.ini --server https://acme-v02.api.letsencrypt.org/directory --agree-tos -d *.myDOMAIN.se.`

However, when I try to set it up automatically using a "/etc/letsencrypt/renewal/myDOMAIN.se.conf configuration file, I run into complications. I cannot get it to identify the "certbot-loopia:auth-credentials" argument. I have tried the different wording in the readme on this from ""certbot_loopia:auth_credentials", "certbot-loopia:credentials" and "certbot_loopia:credentials" but I always get errors looking at `journalctl -u certbot-renewal.service`

The error is:
`Renewal configuration file /etc/letsencrypt/renewal/myDOMAIN.conf (cert: myDOMAIN.se) produced an unexpected error: 'Namespace' object has no attribute 'certbot_loopia:auth_credentials'. Skipping`

My myDOMAIN.conf file looks like this:

```
# renew_before_expiry = 30 days
version = 0.28.0
archive_dir = /etc/letsencrypt/archive/myDOMAIN.se
cert = /etc/letsencrypt/live/myDOMAIN.se/cert.pem
privkey = /etc/letsencrypt/live/myDOMAIN.se/privkey.pem
chain = /etc/letsencrypt/live/myDOMAIN.se/chain.pem
fullchain = /etc/letsencrypt/live/myDOMAIN.se/fullchain.pem

# Options used in the renewal process
[renewalparams]
authenticator = certbot-loopia:auth
certbot-loopia:auth-credentials = /etc/letsencrypt/credentials.ini
account = d98eab539ee4f9765ac7d4b473edad3f
pref_challs = dns-01,
server = https://acme-v02.api.letsencrypt.org/directory
```

I'm running this in a minimal container running Debian 9 and Nginx.

Thank you for the help and a great tool!

**Comment by runfalk** [comment]
Hi, glad you like it. It could be that you have installed certbot in multiple ways and one version doesn't have the Loopia plugin. Try to remove all certbot deb packages and only install through `pip`.

What does your systemd unit file look like?

**Comment by tb-lund** [comment]
Hi! Thank you for the prompt and helpful reply. This may indeed have been the case. I have now removed the other certbot install. Should do it!
